version: '3.7'

services:

  api-web:
    build: ./app
    command: uvicorn app.main:app --host 0.0.0.0 --port 3000
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nudges
    expose:
      - 5432

volumes:
  postgres_data:
